version: '3.8'

services:
  cosmosdb-sidecar:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Set COSMOS_ENDPOINT to your Cosmos DB account endpoint
      # For local testing with Cosmos DB Emulator, use: https://localhost:8081
      # For Azure Cosmos DB, use: https://your-account.documents.azure.com:443/
      - COSMOS_ENDPOINT=${COSMOS_ENDPOINT:-}
      - COSMOS_KEY=${COSMOS_KEY}
      - COSMOS_DEFAULT_DB=${COSMOS_DEFAULT_DB:-ureca_evo}
      - LOGGING_LEVEL_COM_URECA_COSMOSDB=${LOG_LEVEL:-DEBUG}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    restart: unless-stopped
